name: my-real-estate-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - scikit-learn
  - joblib
  - pytest  # needed if you want to run tests
  - pip
  - pip:
      - azure-ai-ml  # or other PyPI packages not on conda
