name: my-real-estate-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - scikit-learn
  - joblib
  - pytest
  - pip
  - pip:
      - azure-ai-ml
      - azure-identity
