name: CI/CD for Real Estate ML

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # 1) Install and activate your Conda environment automatically
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          environment-file: environment.yml
          activate-environment: my-real-estate-env
          python-version: 3.9
          auto-activate-base: false

      # 2) Now the environment is activated for all subsequent steps
      - name: Run tests
        run: pytest tests/

      - name: Train model
        run: python train.py

      - name: Deploy model to Azure ML
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
          AZURE_ML_WORKSPACE_NAME: ${{ secrets.AZURE_ML_WORKSPACE_NAME }}
          # If needed:
          # AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          # AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          # AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        run: python azure_ml_deploy.py
